# Generated by Django 4.2.3 on 2023-08-08 13:39

from django.db import migrations, models

import django.contrib.auth.validators

class Migration(migrations.Migration):
    
    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
           name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='name')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email_address')),
               ],
        ),
    ]

