# Generated by Django 4.2.3 on 2023-09-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='email',
        ),
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
        
        migrations.RemoveField(
            model_name='members',
            name='username',
        ),
    ]
