# Generated by Django 4.2.3 on 2023-08-08 13:39

from django.db import migrations, models

import django.contrib.auth.validators

class Migration(migrations.Migration):
    
    dependencies = [
        ('students', '0003_remove_members_email_remove_members_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
           name='pending_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=150,verbose_name='username')),
                ('project_title', models.CharField(max_length=150,verbose_name='username')),
                ('Upload_File', models.FileField(upload_to='Upload_File')),
                ('Client_email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
               ],
        ),
    ]

