# Generated by Django 4.2.3 on 2023-09-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_pending_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pending_projects',
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.EmailField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
