# Generated by Django 4.2.3 on 2023-09-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_category_pending_projects_alter_members_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_projects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
