# Generated by Django 4.2.3 on 2023-09-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_pending_projects_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_projects',
            name='Upload_File',
            field=models.ImageField(default="NOT UPLOADED", upload_to='Upload_File'),
            preserve_default=False,
        ),
    ]
