# Generated by Django 4.2.3 on 2023-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_pending_projects_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_projects',
            name='Upload_File',
            field=models.FileField(blank=True, null=True, upload_to='Upload_File'),
        ),
    ]
