# Generated by Django 4.2.3 on 2023-10-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_pending_projects_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='members',
        ),
    ]
