# Generated by Django 4.2.3 on 2023-10-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_delete_category_delete_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
