# Generated by Django 4.2.3 on 2023-10-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_usermodel_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='roll',
            field=models.IntegerField(default=1),
        ),
    ]
