# Generated by Django 4.2.3 on 2023-10-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_passwordtoken_reset_password_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('Client_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='adminpanel',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
