# Generated by Django 4.2.3 on 2023-10-10 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_requirementmodel_alter_adminpanel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
