# Generated by Django 4.2.3 on 2023-10-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_requirementmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
