# Generated by Django 4.2.3 on 2023-10-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_requirementmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='roll',
            field=models.IntegerField(choices=[('', 'Choose...'), ('2', 'Leader'), ('1', 'Developer')]),
        ),
    ]
