# Generated by Django 4.2.3 on 2023-10-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_usermodel_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementmodel',
            name='project_Description',
            field=models.TextField(default='Nullli', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirementmodel',
            name='project_Technology',
            field=models.CharField(default='nulii', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='roll',
            field=models.IntegerField(choices=[('', 'Choose...'), (2, 'Leader'), (1, 'Developer')]),
        ),
    ]
