# Generated by Django 4.2.3 on 2023-10-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_requirementmodel_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementmodel',
            name='assigned_dev',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
