# Generated by Django 4.2.3 on 2023-10-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_usermodel_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementmodel',
            name='project_Technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='technology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
