# Generated by Django 4.2.3 on 2023-11-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_remove_pending_projects_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_projects',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
