# Generated by Django 4.2.3 on 2023-11-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_pending_projects_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pending_projects',
            name='deadline',
        ),
        migrations.AddField(
            model_name='requirementmodel',
            name='DEVdeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
