# Generated by Django 4.2.3 on 2023-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_reviewmodel_alter_reset_password_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
