# Generated by Django 4.2.3 on 2023-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_alter_reviewmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Assigned_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
